# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blasphemy}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tomasz Stachewicz"]
  s.date = %q{2011-10-15}
  s.description = %q{Surprise everyone by stubbing placeholder texts with something more original than boring "Lorem ipsum dolor sit amet". Embrace and extend, creating own wordlists for hilarious (or blasphemous or whatever you like) generated texts.}
  s.email = %q{tomekrs@o2.pl}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "blasphemy.gemspec",
    "lib/blasphemy.rb",
    "test/helper.rb",
    "test/test_blasphemy.rb"
  ]
  s.homepage = %q{http://github.com/tomash/blasphemy}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A different Lorem Ipsum generator, lightweight and extensible}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

